# Repository
repo_name: cudy-docs
repo_url: https://github.com/cudytech-pr/User-Guide
edit_uri: ""

site_name: Docs
site_description: Documentation for Cudy Products
site_author: Cudy Docs
site_url: https://docs.cudy.com
site_dir: site
copyright: © 2025, Shenzhen Cudy Technology Co., Ltd.

docs_dir: docs

theme: 
  name: material
  logo: images/cudyicon.webp
  custom_dir: overrides
  features:
    - search.highlight
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - footer.social
  palette:
    # Light Mode
    - scheme: default 
      primary: "#008CFF"  
      accent: "#008CFF"  
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode 
    # Dark Mode 
    - scheme: slate 
      primary: "#006BB3"  
      accent: "#006BB3"  
      toggle:
        icon: material/toggle-switch 
        name: Switch to light mode 
  favicon: images/favicon.ico 

# Plugins
plugins:
  - search
  - include-markdown
  - glightbox 

# Customization
extra:
  # analytics:
  #   provider: google
  #   property: G-PEZ9H4DS1X
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:support@cudy.com
    - icon: fontawesome/solid/globe
      link: https://www.cudy.com
    - icon: fontawesome/brands/github
      link: https://github.com/cudytech-pr
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/cudytech/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cudytech
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCi9XeBubGtEazL6KxO8In6w
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cudytech
  cname: docs.cudy.com

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.css

  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.umd.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/analytics.js
  - javascripts/extra.js
  - javascripts/cookieconsent.js

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      permalink: true
  - admonition

nav:
  - Home: index.md
  - User Guide:
    - Overview: user_guide/index.md
    - WR3600:
      - WR3600: user_guide/wr3600/index.md
      - Overview: user_guide/wr3600/overview.md
      - Connect: user_guide/wr3600/connection.md
      - Quick Setup: user_guide/wr3600/quick_setup.md
      - Management:
        - System Status: user_guide/wr3600/status.md
        - General Settings:
          - WAN Mode: user_guide/wr3600/wan.md
          - Wireless: user_guide/wr3600/wireless.md
          - VPN: user_guide/wr3600/vpn.md
          - Captive Portal: user_guide/wr3600/captive_portal.md
          - Firmware: user_guide/wr3600/firmware.md
        - Advanced Settings:
          - Network: user_guide/wr3600/network.md
          - Security: user_guide/wr3600/security.md
          - System: user_guide/wr3600/system.md
        - Parental Control: user_guide/wr3600/parental_control.md
        - Diagnostic Tools: user_guide/wr3600/diagnostic_tools.md
    - GP1200: 
      - GP1200: user_guide/gp1200/index.md
      - Overview: user_guide/gp1200/overview.md
      - Connect: user_guide/gp1200/connection.md
      - Quick Setup: user_guide/gp1200/quick_setup.md 
      - Management:
        - Status: user_guide/gp1200/pon_status.md 
        - LAN: user_guide/gp1200/pon_lan.md 
        - WLAN: user_guide/gp1200/pon_wlan.md 
        - WAN: user_guide/gp1200/pon_wan.md 
        - Services: user_guide/gp1200/pon_service.md 
        - Advance: user_guide/gp1200/pon_advance.md
        - Admin: user_guide/gp1200/pon_admin.md  
        - Diagnostics: user_guide/gp1200/pon_diagnostics.md 
        - Statistics: user_guide/gp1200/pon_statistics.md 
    - IR04: 
      - IR04: user_guide/ir04/index.md
      - Overview: user_guide/ir04/overview.md  
      - Install & Power: user_guide/ir04/install_power.md
      - Quick Setup: user_guide/ir04/quick_setup.md
      - Management:
        - System Status: user_guide/ir04/status.md
        - General Settings:
          - Cellular: user_guide/ir04/cellular.md
          - Serial Service: user_guide/ir04/serial_service.md
          - Input/Output: user_guide/ir04/input_output.md
          - WISP: user_guide/ir04/wisp.md
          - Wireless 2.4G: user_guide/ir04/wireless_2.4g.md
          - VPN: user_guide/ir04/vpn.md
          - Firmware: user_guide/ir04/firmware.md
        - Advanced Settings: 
          - Network: user_guide/ir04/network.md
          - Security: user_guide/ir04/security.md
          - System: user_guide/ir04/system.md
        - Diagnostic Tools: user_guide/ir04/diagnostic_tools.md        
    - GS1024E:
      - GS1024E: user_guide/gs1024e/index.md
      - Overview: user_guide/gs1024e/overview.md  
      - Install: user_guide/gs1024e/installation.md
      - Management:
        - Log In/Out: user_guide/gs1024e/log_in_out.md
        - System Manage: user_guide/gs1024e/system_manage.md
        - Port Management: user_guide/gs1024e/port_management.md
        - Protocol Management: user_guide/gs1024e/protocol_management.md
        - VLAN: user_guide/gs1024e/vlan.md
        - QoS: user_guide/gs1024e/qos.md
        - Tools: user_guide/gs1024e/tools.md
    - C200P:
      - C200P: user_guide/c200p/index.md
      - Overview: user_guide/c200p/overview.md
      - Connect: user_guide/c200p/connection.md
      - Quick Setup: user_guide/c200p/quick_setup.md
      - Management:
        - System Status: user_guide/c200p/status.md
        - General Settings:
          - AP Management: user_guide/c200p/ap_management.md
          - Wireless: user_guide/c200p/wireless.md
          - Captive Portal: user_guide/c200p/captive_portal.md
          - WAN Mode: user_guide/c200p/wan.md
          - PoE: user_guide/c200p/poe.md
          - VPN: user_guide/c200p/vpn.md
          - Firmware: user_guide/c200p/firmware.md
        - Advanced Settings:
          - Network: user_guide/c200p/network.md
          - Security: user_guide/c200p/security.md
          - System: user_guide/c200p/system.md
        - Diagnostic Tools: user_guide/c200p/diagnostic_tools.md          
  - Tutorials:
    - Turtorials: tutorials/index.md    
  - FAQ:
    - FAQ: faq/index.md